import HeaderLayout from "@/components/single-instance/header/HeaderLayout.component";
import FooterLayout from "@/components/single-instance/footer/FooterLayout.component";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className="font-Dana-medium bg-primaryBg">
        <HeaderLayout />
        {children}
        <FooterLayout />
      </body>
    </html>
  );
}
